{% set name = "libffi" %}
{% set version = "3.2.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: ftp://sourceware.org/pub/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha1: 280c265b789e041c02e5c97815793dfc283fb1e6
  patches:
    - configure_includedir_option.patch
    - 0002-Don-t-define-FFI_COMPLEX_TYPEDEF-ifndef-FFI_TARGET_H.patch  # [win]
    - 0003-Win64-remove-two-SHORT-annotations.patch                    # [win]
    - 0004-Update-to-libtool-2.4.6.34.patch                            # [win]
#    - 9999-Hack-verbose-libtool.patch                                 # [win]

build:
  number: 3

requirements:
  build:
    - posix                     # [win]
    - {{posix}}automake-wrapper # [win]
    - {{native}}toolchain       # [win]
    - {{posix}}automake         # [not win]
    - {{posix}}autoconf
    - {{posix}}libtool

test:
  commands:
    - test -e $PREFIX/lib/libffi.so  # [linux]
    - test -e $PREFIX/lib/libffi.a  # [unix]
    - test -e $PREFIX/lib/libffi.dylib  # [osx]
    - test -e $PREFIX/include/ffi.h
    - test -e $PREFIX/include/ffitarget.h

about:
  home: https://sourceware.org/libffi/
  license: Custom
  summary: A Portable Foreign Function Interface Library.

extra:
  recipe-maintainers:
    - stefan-balke
    - scopatz
